# syntax=docker/dockerfile:1

FROM golang:1.20.13-bullseye

COPY . /optimizeImageSize

WORKDIR /optimizeImageSize/app

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-w -s"  -o /app /optimizeImageSize/app/main.go

RUN rm -r *

CMD ["/app"]